LOCAL_DIR := $(GET_LOCAL_DIR)

CFLAGS += -DLZ4_HEAPMODE=0 -DLZ4HC_HEAPMODE=0 -DLZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION=1

OBJS += \
	$(LOCAL_DIR)/lz4.o \
	$(LOCAL_DIR)/lz4hc.o \
	$(LOCAL_DIR)/lz4frame.o \
	$(LOCAL_DIR)/xxhash.o \
