LOCAL_DIR := $(GET_LOCAL_DIR)

include $(LOCAL_DIR)/msm8916.mk
include $(LOCAL_DIR)/lk2nd-common.mk
include $(LOCAL_DIR)/lk2nd-msm8916-common.mk

APPSBOOTHEADER: $(OUTBOOTIMG) $(OUTBOOTIMGADTB) $(OUTODINTAR)
ANDROID_BOOT_BASE := 0x80000000
