# top level project rules for the msm8974 project
#

set(TARGET msm8974 CACHE STRING "TARGET from lk makefiles" FORCE)

#MODULES += app/aboot

set(EMMC_BOOT 1 CACHE STRING "" FORCE)
set(ENABLE_SDHCI_SUPPORT 1 CACHE STRING "" FORCE)
set(ENABLE_USB30_SUPPORT 1 CACHE STRING "" FORCE)

#Disable thumb mode
set(ENABLE_THUMB 0 CACHE STRING "" FORCE)

target_compile_definitions(lk PRIVATE
	WITH_DEBUG_UART=1
	DEVICE_TREE=1
	CRYPTO_BAM=1
	CRYPTO_REG_ACCESS=1
	ABOOT_IGNORE_BOOT_HEADER_ADDRS=1
	ABOOT_FORCE_KERNEL_ADDR=0x00008000
	ABOOT_FORCE_RAMDISK_ADDR=0x02000000
	ABOOT_FORCE_TAGS_ADDR=0x01e00000
	ABOOT_FORCE_KERNEL64_ADDR=0x00080000
	_EMMC_BOOT=1
	MMC_SDHCI_SUPPORT=1
	USB30_SUPPORT=1
)
