#!/bin/sh

PROJECTS="msm8226 msm8974 apq8084 msm8994 mdm9630 mdm9640 msm8610 msm8916 msm8996"
FAILED=""

for p in $PROJECTS; do
	PROJECT=$p make -j2 || FAILED="$FAILED $p"
done

if [ "$FAILED" != "" ]; then
	echo
	echo some projects have failed to build:
	echo $FAILED
fi
