/* Copyright (c) 2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _R69431_720P_VIDEO_H_
#define _R69431_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config r69431_720p_video_panel_data = {
	"qcom,mdss_dsi_r69431_720p_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution r69431_720p_video_panel_res = {
	720, 1280, 140, 20, 10, 0, 13, 11, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info r69431_720p_video_color = {
	24, 2, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char r69431_720p_video_on_cmd0[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB0, 0x00, 0xFF, 0xFF,
};

static char r69431_720p_video_on_cmd1[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xD6, 0x01, 0xFF, 0xFF,
};

static char r69431_720p_video_on_cmd2[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB3, 0x1C, 0xFF, 0xFF,
};

static char r69431_720p_video_on_cmd3[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB0, 0x03, 0xFF, 0xFF,
};

static char r69431_720p_video_on_cmd4[] = {
	0x29, 0x00, 0x05, 0x80,
};

static char r69431_720p_video_on_cmd5[] = {
	0x11, 0x00, 0x05, 0x80,
};

static struct mipi_dsi_cmd r69431_720p_video_on_command[] = {
	{0x8, r69431_720p_video_on_cmd0, 0x00},
	{0x8, r69431_720p_video_on_cmd1, 0x00},
	{0x8, r69431_720p_video_on_cmd2, 0x00},
	{0x8, r69431_720p_video_on_cmd3, 0x00},
	{0x4, r69431_720p_video_on_cmd4, 0x00},
	{0x4, r69431_720p_video_on_cmd5, 0x78},
};

#define R69431_720P_VIDEO_ON_COMMAND 6

static struct command_state r69431_720p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info r69431_720p_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info r69431_720p_video_video_panel = {
	0xA, 0, 0, 0, 1, 1, 1, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration r69431_720p_video_lane_config = {
	3, 0, 1, 1, 1, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t r69431_720p_video_timings[] = {
	0x9B, 0x22, 0x18, 0x00, 0x4A, 0x4C, 0x1C, 0x26, 0x1D, 0x03, 0x04, 0x00
};

static struct panel_timing r69431_720p_video_timing_info = {
	0, 4, 4, 0x1F
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence r69431_720p_video_reset_seq = {
	{1, 0, 1, }, {5, 5, 10, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight r69431_720p_video_backlight = {
	0, 1, 255, 0, 0, 0
};

#define R69431_720P_VIDEO_SIGNATURE 0x9431

#endif /*_R69431_720P_VIDEO_H_*/
