/* Copyright (c) 2013-2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_HX8389B_QHD_VIDEO_H_
#define _PANEL_HX8389B_QHD_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config hx8389b_qhd_video_panel_data = {
	"qcom,mdss_dsi_hx8389b_qhd_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution hx8389b_qhd_video_panel_res = {
	540, 960, 60, 39, 39, 0, 9, 13, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info hx8389b_qhd_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char hx8389b_qhd_video_on_cmd0[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xB9, 0xFF, 0x83, 0x89,
};

static char hx8389b_qhd_video_on_cmd1[] = {
	0xCC, 0x02, 0x15, 0x80
};

static char hx8389b_qhd_video_on_cmd2[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xC0, 0x43, 0x17, 0xFF,
};

static char hx8389b_qhd_video_on_cmd3[] = {
	0x08, 0x00, 0x39, 0xC0,
	0xBA, 0x41, 0x93, 0x00,
	0x16, 0xA4, 0x10, 0x18,
};

static char hx8389b_qhd_video_on_cmd4[] = {
	0x14, 0x00, 0x39, 0xC0,
	0xB1, 0x00, 0x00, 0x06,
	0xEB, 0x59, 0x10, 0x11,
	0xEE, 0xEE, 0x3A, 0x42,
	0x3F, 0x3F, 0x43, 0x01,
	0x5A, 0xF6, 0x00, 0xE6,
};

static char hx8389b_qhd_video_on_cmd5[] = {
	0x08, 0x00, 0x39, 0xC0,
	0xB2, 0x00, 0x00, 0x78,
	0x0C, 0x07, 0x3F, 0x80,
};

static char hx8389b_qhd_video_on_cmd6[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xb7, 0x00, 0x00, 0x50,
};

static char hx8389b_qhd_video_on_cmd7[] = {
	0x18, 0x00, 0x39, 0xC0,
	0xB4, 0x80, 0x08, 0x00,
	0x32, 0x10, 0x04, 0x32,
	0x10, 0x00, 0x32, 0x10,
	0x00, 0x37, 0x0a, 0x40,
	0x08, 0x37, 0x00, 0x46,
	0x02, 0x58, 0x58, 0x02,
};

static char hx8389b_qhd_video_on_cmd8[] = {
	0x39, 0x00, 0x39, 0xC0,
	0xD5, 0x00, 0x00, 0x00,
	0x00, 0x01, 0x00, 0x00,
	0x00, 0x60, 0x00, 0x99,
	0x88, 0xAA, 0xBB, 0x88,
	0x23, 0x88, 0x01, 0x88,
	0x67, 0x88, 0x45, 0x01,
	0x23, 0x88, 0x88, 0x88,
	0x88, 0x88, 0x88, 0x99,
	0xBB, 0xAA, 0x88, 0x54,
	0x88, 0x76, 0x88, 0x10,
	0x88, 0x32, 0x32, 0x10,
	0x88, 0x88, 0x88, 0x88,
	0x88, 0x3C, 0x04, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0xFF, 0xFF, 0xFF,
};

static char hx8389b_qhd_video_on_cmd9[] = {
	0x23, 0x00, 0x39, 0xC0,
	0xE0, 0x05, 0x11, 0x16,
	0x35, 0x3F, 0x3F, 0x21,
	0x43, 0x07, 0x0C, 0x0F,
	0x11, 0x12, 0x10, 0x10,
	0x1D, 0x18, 0x05, 0x11,
	0x16, 0x35, 0x3F, 0x3F,
	0x21, 0x43, 0x07, 0x0C,
	0x0F, 0x11, 0x12, 0x10,
	0x10, 0x1D, 0x18, 0xFF,
};

static char hx8389b_qhd_video_on_cmd10[] = {
	0x80, 0x00, 0x39, 0xC0,
	0xC1, 0x01, 0x00, 0x07,
	0x13, 0x21, 0x29, 0x2F,
	0x34, 0x3B, 0x42, 0x48,
	0x50, 0x58, 0x61, 0x69,
	0x71, 0x79, 0x81, 0x88,
	0x90, 0x98, 0xA0, 0xA9,
	0xB1, 0xB9, 0xC1, 0xC8,
	0xCE, 0xD6, 0xDF, 0xE6,
	0xEF, 0xF7, 0xFF, 0x0E,
	0x5A, 0x73, 0x69, 0x36,
	0x8E, 0x69, 0x5F, 0xC0,
	0x00, 0x07, 0x13, 0x21,
	0x29, 0x2F, 0x34, 0x3B,
	0x42, 0x48, 0x50, 0x58,
	0x61, 0x69, 0x71, 0x79,
	0x81, 0x88, 0x90, 0x98,
	0xA0, 0xA9, 0xB1, 0xB9,
	0xC1, 0xC8, 0xCE, 0xD6,
	0xDF, 0xE6, 0xEF, 0xF7,
	0xFF, 0x0E, 0x5A, 0x73,
	0x69, 0x36, 0x8E, 0x69,
	0x5F, 0xC0, 0x00, 0x07,
	0x13, 0x21, 0x29, 0x2F,
	0x34, 0x3B, 0x42, 0x48,
	0x50, 0x58, 0x61, 0x69,
	0x71, 0x79, 0x81, 0x88,
	0x90, 0x98, 0xA0, 0xA9,
	0xB1, 0xB9, 0xC1, 0xC8,
	0xCE, 0xD6, 0xDF, 0xE6,
	0xEF, 0xF7, 0xFF, 0x0E,
	0x5A, 0x73, 0x69, 0x36,
	0x8E, 0x69, 0x5F, 0xC0,
};

static char hx8389b_qhd_video_on_cmd11[] = {
	0x05, 0x00, 0x39, 0xC0,
	0xB6, 0x00, 0x88, 0x00,
	0x88, 0xFF, 0xFF, 0xFF,
};

static char hx8389b_qhd_video_on_cmd12[] = {
	0x11, 0x00, 0x05, 0x80
};

static char hx8389b_qhd_video_on_cmd13[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd hx8389b_qhd_video_on_command[] = {
	{0x8, hx8389b_qhd_video_on_cmd0, 0x0A},
	{0x4, hx8389b_qhd_video_on_cmd1, 0x01},
	{0x8, hx8389b_qhd_video_on_cmd2, 0x01},
	{0xc, hx8389b_qhd_video_on_cmd3, 0x01},
	{0x18, hx8389b_qhd_video_on_cmd4, 0x01},
	{0xc, hx8389b_qhd_video_on_cmd5, 0x01},
	{0x8, hx8389b_qhd_video_on_cmd6, 0x01},
	{0x1c, hx8389b_qhd_video_on_cmd7, 0x01},
	{0x40, hx8389b_qhd_video_on_cmd8, 0x01},
	{0x28, hx8389b_qhd_video_on_cmd9, 0x01},
	{0x84, hx8389b_qhd_video_on_cmd10, 0x05},
	{0xc, hx8389b_qhd_video_on_cmd11, 0x01},
	{0x4, hx8389b_qhd_video_on_cmd12, 0x78},
	{0x4, hx8389b_qhd_video_on_cmd13, 0x32}
};

#define HX8389B_QHD_VIDEO_ON_COMMAND 14


static char hx8389b_qhd_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char hx8389b_qhd_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd hx8389b_qhd_video_off_command[] = {
	{0x4, hx8389b_qhd_videooff_cmd0, 0x32},
	{0x4, hx8389b_qhd_videooff_cmd1, 0x78}
};

#define HX8389B_QHD_VIDEO_OFF_COMMAND 2


static struct command_state hx8389b_qhd_video_state = {
	0, 0
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info hx8389b_qhd_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info hx8389b_qhd_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration hx8389b_qhd_video_lane_config = {
	2, 1, 1, 1, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t hx8389b_qhd_video_timings[] = {
	0x87, 0x1E, 0x14, 0x00, 0x44, 0x4B, 0x19, 0x21, 0x22, 0x03, 0x04, 0x00
};

static struct panel_timing hx8389b_qhd_video_timing_info = {
	0, 4, 0x04, 0x1b
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence hx8389b_qhd_video_reset_seq = {
  { 2, 0, 2, }, { 20, 2, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight hx8389b_qhd_video_backlight = {
  0, 1, 255, 0, 1, 0
};

#endif /*_PANEL_HX8389B_QHD_VIDEO_H_*/
