/* Copyright (c) 2013-2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TRULY_WVGA_VIDEO_H_

#define _PANEL_TRULY_WVGA_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config truly_wvga_video_panel_data = {
  "qcom,mdss_dsi_truly_wvga_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution truly_wvga_video_panel_res = {
  480, 800, 160, 40, 8, 0, 12, 10, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info truly_wvga_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char truly_wvga_video_on_cmd0[] = {
0x01, 0x00, 0x05, 0x80 };


static char truly_wvga_video_on_cmd1[] = {
0xb0, 0x04, 0x23, 0x80 };


static char truly_wvga_video_on_cmd2[] = {
0x03, 0x00, 0x29, 0xC0,
0xb3, 0x02, 0x00, 0xFF,  };


static char truly_wvga_video_on_cmd3[] = {
0xbd, 0x00, 0x23, 0x80 };


static char truly_wvga_video_on_cmd4[] = {
0x03, 0x00, 0x29, 0xC0,
0xc0, 0x18, 0x66, 0xFF,  };


static char truly_wvga_video_on_cmd5[] = {
0x10, 0x00, 0x29, 0xC0,
0xc1, 0x23, 0x31, 0x99,
0x21, 0x20, 0x00, 0x30,
0x28, 0x0c, 0x0c, 0x00,
0x00, 0x00, 0x21, 0x01,
 };


static char truly_wvga_video_on_cmd6[] = {
0x07, 0x00, 0x29, 0xC0,
0xc2, 0x00, 0x06, 0x06,
0x01, 0x03, 0x00, 0xFF,  };


static char truly_wvga_video_on_cmd7[] = {
0x19, 0x00, 0x29, 0xC0,
0xc8, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd8[] = {
0x19, 0x00, 0x29, 0xC0,
0xc9, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd9[] = {
0x19, 0x00, 0x29, 0xC0,
0xca, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0x04, 0x10, 0x18,
0x20, 0x2e, 0x46, 0x3c,
0x28, 0x1f, 0x18, 0x10,
0x04, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd10[] = {
0x11, 0x00, 0x29, 0xC0,
0xd0, 0x29, 0x03, 0xce,
0xa6, 0x00, 0x43, 0x20,
0x10, 0x01, 0x00, 0x01,
0x01, 0x00, 0x03, 0x01,
0x00, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd11[] = {
0x08, 0x00, 0x29, 0xC0,
0xd1, 0x18, 0x0C, 0x23,
0x03, 0x75, 0x02, 0x50,
 };


static char truly_wvga_video_on_cmd12[] = {
0xd3, 0x11, 0x23, 0x80 };


static char truly_wvga_video_on_cmd13[] = {
0x03, 0x00, 0x29, 0xC0,
0xd5, 0x2a, 0x2a, 0xFF,  };


static char truly_wvga_video_on_cmd14[] = {
0x03, 0x00, 0x29, 0xC0,
0xde, 0x01, 0x51, 0xFF,  };


static char truly_wvga_video_on_cmd15[] = {
0xe6, 0x51, 0x23, 0x80 };


static char truly_wvga_video_on_cmd16[] = {
0xfa, 0x03, 0x23, 0x80 };


static char truly_wvga_video_on_cmd17[] = {
0xd6, 0x28, 0x23, 0x80 };


static char truly_wvga_video_on_cmd18[] = {
0x05, 0x00, 0x39, 0xC0,
0x2a, 0x00, 0x00, 0x01,
0xdf, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd19[] = {
0x05, 0x00, 0x39, 0xC0,
0x2b, 0x00, 0x00, 0x03,
0x1f, 0xFF, 0xFF, 0xFF,  };


static char truly_wvga_video_on_cmd20[] = {
0x35, 0x00, 0x15, 0x80 };


static char truly_wvga_video_on_cmd21[] = {
0x03, 0x00, 0x39, 0xC0,
0x44, 0x00, 0x50, 0xFF,  };


static char truly_wvga_video_on_cmd22[] = {
0x36, 0xc1, 0x15, 0x80 };


static char truly_wvga_video_on_cmd23[] = {
0x3a, 0x77, 0x15, 0x80 };


static char truly_wvga_video_on_cmd24[] = {
0x11, 0x00, 0x05, 0x80 };


static char truly_wvga_video_on_cmd25[] = {
0x29, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd truly_wvga_video_on_command[] = {
{ 0x4 , truly_wvga_video_on_cmd0},
{ 0x4 , truly_wvga_video_on_cmd1},
{ 0x8 , truly_wvga_video_on_cmd2},
{ 0x4 , truly_wvga_video_on_cmd3},
{ 0x8 , truly_wvga_video_on_cmd4},
{ 0x14 , truly_wvga_video_on_cmd5},
{ 0xc , truly_wvga_video_on_cmd6},
{ 0x20 , truly_wvga_video_on_cmd7},
{ 0x20 , truly_wvga_video_on_cmd8},
{ 0x20 , truly_wvga_video_on_cmd9},
{ 0x18 , truly_wvga_video_on_cmd10},
{ 0xc , truly_wvga_video_on_cmd11},
{ 0x4 , truly_wvga_video_on_cmd12},
{ 0x8 , truly_wvga_video_on_cmd13},
{ 0x8 , truly_wvga_video_on_cmd14},
{ 0x4 , truly_wvga_video_on_cmd15},
{ 0x4 , truly_wvga_video_on_cmd16},
{ 0x4 , truly_wvga_video_on_cmd17},
{ 0xc , truly_wvga_video_on_cmd18},
{ 0xc , truly_wvga_video_on_cmd19},
{ 0x4 , truly_wvga_video_on_cmd20},
{ 0x8 , truly_wvga_video_on_cmd21},
{ 0x4 , truly_wvga_video_on_cmd22},
{ 0x4 , truly_wvga_video_on_cmd23},
{ 0x4 , truly_wvga_video_on_cmd24},
{ 0x4 , truly_wvga_video_on_cmd25}
};
#define TRULY_WVGA_VIDEO_ON_COMMAND 26


static char truly_wvga_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char truly_wvga_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd truly_wvga_video_off_command[] = {
{ 0x4 , truly_wvga_videooff_cmd0},
{ 0x4 , truly_wvga_videooff_cmd1}
};
#define TRULY_WVGA_VIDEO_OFF_COMMAND 2


static struct command_state truly_wvga_video_state = {
  0, 0
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info truly_wvga_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info truly_wvga_video_video_panel = {
  0, 0, 0, 0, 1, 1, 1, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration truly_wvga_video_lane_config = {
  2, 0, 1, 1, 0, 0, 0
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t truly_wvga_video_timings[] = {
  0x5D, 0x12, 0x0C, 0x00, 0x33, 0x38, 0x10, 0x16, 0x1E, 0x03, 0x04, 0x00
};

static struct panel_timing truly_wvga_video_timing_info = {
  0, 4, 0x04, 0x1b
};

/*---------------------------------------------------------------------------*/
/* Panel Reset Sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence truly_wvga_video_reset_seq = {
  { 2, 0, 2, }, { 20, 2, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight truly_wvga_video_backlight = {
  0, 1, 255, 0, 1, 0
};


#endif /*_PANEL_TRULY_WVGA_VIDEO_H_*/
