/* Copyright (c) 2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_R61318_HD_VIDEO_H_
#define _PANEL_R61318_HD_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config r61318_hd_video_panel_data = {
	"qcom,mdss_dsi_r61318_hd_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution r61318_hd_video_panel_res = {
	720, 1280, 40, 30, 12, 0, 18, 9, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info r61318_hd_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char r61318_hd_video_on_cmd0[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB0, 0x00, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd1[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB3, 0x00, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd2[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xB6, 0x32, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd3[] = {
	0x02, 0x00, 0x39, 0xC0,
	0x36, 0x0A, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd4[] = {
	0x07, 0x00, 0x29, 0xC0,
	0xC0, 0x20, 0xB2, 0x0D,
	0x10, 0x02, 0x80, 0xFF,
};

static char r61318_hd_video_on_cmd5[] = {
	0x08, 0x00, 0x29, 0xC0,
	0xC1, 0x35, 0x85, 0x85,
	0x85, 0x10, 0x10, 0x33,

};

static char r61318_hd_video_on_cmd6[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xC3, 0x20, 0x0F, 0x00,

};

static char r61318_hd_video_on_cmd7[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xC4, 0xBC, 0xD2, 0x00,

};

static char r61318_hd_video_on_cmd8[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xC5, 0x06, 0x03, 0x1D,

};

static char r61318_hd_video_on_cmd9[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xC6, 0x21, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd10[] = {
	0x1D, 0x00, 0x29, 0xC0,
	0xC8, 0x60, 0x0E, 0x08,
	0x62, 0x90, 0x52, 0x95,
	0x54, 0x49, 0x29, 0x84,
	0x90, 0xA2, 0x4A, 0x29,
	0x45, 0x15, 0x42, 0x48,
	0xA9, 0xA4, 0xA4, 0xAA,
	0x85, 0x0c, 0x11, 0xc0,
	0x31, 0xFF, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd11[] = {
	0x1F, 0x00, 0x29, 0xC0,
	0xCA, 0x02, 0x0A, 0x0F,
	0x15, 0x1B, 0x20, 0x23,
	0x1F, 0x24, 0x24, 0x21,
	0x1A, 0x15, 0x0F, 0x01,
	0x02, 0x0A, 0x0F, 0x15,
	0x1B, 0x20, 0x23, 0x1F,
	0x24, 0x24, 0x21, 0x1A,
	0x15, 0x0F, 0x01, 0xFF,
};

static char r61318_hd_video_on_cmd12[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xCD, 0x00, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd13[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xE5, 0x02, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd14[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xD0, 0x05, 0x89, 0x1A,
};

static char r61318_hd_video_on_cmd15[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xD1, 0x03, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd16[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xD2, 0x81, 0x1F, 0xFF,
};

static char r61318_hd_video_on_cmd17[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xD4, 0x4D, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd18[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xD5, 0x34, 0x34, 0xFF,
};

static char r61318_hd_video_on_cmd19[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xBB, 0x2E, 0xFF, 0xFF
};

static char r61318_hd_video_on_cmd20[] = {
	0x02, 0x00, 0x39, 0xC0,
	0x53, 0x2C, 0xFF, 0xFF
};

static char r61318_hd_video_on_cmd21[] = {
	0x02, 0x00, 0x39, 0xC0,
	0x51, 0xff, 0xFF, 0xFF,
};

static char r61318_hd_video_on_cmd22[] = {
	0x11, 0x00, 0x05, 0x80
};

static char r61318_hd_video_on_cmd23[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd r61318_hd_video_on_command[] = {
	{0x8, r61318_hd_video_on_cmd0, 0x00},
	{0x8, r61318_hd_video_on_cmd1, 0x00},
	{0x8, r61318_hd_video_on_cmd2, 0x00},
	{0x8, r61318_hd_video_on_cmd3, 0x00},
	{0xc, r61318_hd_video_on_cmd4, 0x00},
	{0xc, r61318_hd_video_on_cmd5, 0x00},
	{0x8, r61318_hd_video_on_cmd6, 0x00},
	{0x8, r61318_hd_video_on_cmd7, 0x00},
	{0x8, r61318_hd_video_on_cmd8, 0x00},
	{0x8, r61318_hd_video_on_cmd9, 0x00},
	{0x24, r61318_hd_video_on_cmd10, 0x00},
	{0x24, r61318_hd_video_on_cmd11, 0x00},
	{0x8, r61318_hd_video_on_cmd12, 0x00},
	{0x8, r61318_hd_video_on_cmd13, 0x00},
	{0x8, r61318_hd_video_on_cmd14, 0x00},
	{0x8, r61318_hd_video_on_cmd15, 0x00},
	{0x8, r61318_hd_video_on_cmd16, 0x00},
	{0x8, r61318_hd_video_on_cmd17, 0x00},
	{0x8, r61318_hd_video_on_cmd18, 0x00},
	{0x8, r61318_hd_video_on_cmd19, 0x00},
	{0x8, r61318_hd_video_on_cmd20, 0x00},
	{0x8, r61318_hd_video_on_cmd21, 0x00},
	{0x4, r61318_hd_video_on_cmd22, 0x78},
	{0x4, r61318_hd_video_on_cmd23, 0x32}
};

#define R61318_HD_VIDEO_ON_COMMAND 24


static char r61318_hd_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char r61318_hd_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd r61318_hd_video_off_command[] = {
	{0x4, r61318_hd_videooff_cmd0, 0x32},
	{0x4, r61318_hd_videooff_cmd1, 0x78}
};

#define R61318_HD_VIDEO_OFF_COMMAND 2


static struct command_state r61318_hd_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info r61318_hd_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info r61318_hd_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration r61318_hd_video_lane_config = {
	4, 0, 1, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t r61318_hd_video_timings[] = {
	0xab, 0x1c, 0x14, 0x00, 0x2a, 0x27, 0x18, 0x1e, 0x21, 0x03, 0x04, 0x00
};

static struct panel_timing r61318_hd_video_timing_info = {
	0, 4, 0x20, 0x2e
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence r61318_hd_video_reset_seq = {
	{1, 0, 1, }, {20, 20, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight r61318_hd_video_backlight = {
	2, 1, 255, 0, 2, "bl_ctrl_dcs"
};

#endif /*_PANEL_R61318_HD_VIDEO_H_*/
