name: Build lk2nd matrix
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      artifacts:
        type: string
        required: true
      exclude:
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - apq8084
          - mdm9607
          - mdm9640
          - msm8226
          - msm8610
          - msm8660
          - msm8909
          - msm8916
          - msm8952
          - msm8953
          - msm8960
          - msm8974
          - msm8994
          - msm8996
        exclude:
          - platform: ${{ inputs.exclude }}

    uses: ./.github/workflows/lk2nd.yml
    with:
      project: ${{ inputs.project }}
      platform: ${{ matrix.platform }}
      artifacts: ${{ inputs.artifacts }}
